# Project: Memo1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = Memo_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/ProgramC/Dev-Cpp/MinGW64/lib" -L"D:/ProgramC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -lgraphics64  -lgdiplus -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lwinmm
INCS     = -I"D:/ProgramC/Dev-Cpp/MinGW64/include" -I"D:/ProgramC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/ProgramC/Dev-Cpp/MinGW64/include" -I"D:/ProgramC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/ProgramC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Memo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Memo_private.res: Memo_private.rc 
	$(WINDRES) -i Memo_private.rc --input-format=rc -o Memo_private.res -O coff 

